project:
  name: sample-app
  version: 1.2.3

deploy:
  environment: staging
  region: ap-northeast-1
  bucket: my-sample-app-bucket

default:
  lang: "ja"
  directory: ./mnt/pdf
  processed_pdf: ./mnt/text/pdf
  processed_text: ./mnt/text/text
  llm_models: ./mnt/models
  interval: 10

pdf:
  author: Coela
  producer: PDF2TEXT
  title: "Sample Title"
  subject: "Sample Subject"
  creator: "Document Scanner"
  customfield: "CustomValue"
  page_option: 0
